<?php
$post = $this->getPost();

$dateFormat = $this->getDateFormat();
?>

<div class="post-page">
    <div class="post-content">
        <div class="post-short-content"><p><font color="#a9a9a9">HealthViet
                    - </font><?php echo strip_tags($post->getShortContent()); ?></p></div>
        <div class="thumbs">
            <img src="<?php echo $post->getImage() ?>"/>
        </div>
        <div class="post-text">
            <?php echo $this->filterContent($post->getContent()); ?>
        </div>
        <div></div>
        <div class="post-data">
            <span class="create-date material-icons-access_time">
                <time><?php echo date($dateFormat, strtotime($post->getCreationTime())); ?></time>
            </span>
            <?php if ($author = $post->getAuthor()): ?>
                <span class="post-author material-icons-person">
                <span class="label"><?php echo __('by '); ?></span>
                <span class="author"><?php echo $author; ?></span>
            </span>
            <?php endif; ?>
            <?php if ($post->getCommentsEnabled()) : ?>
                <span class="post-comments">
                <a href="#post-comments">
                    <span class="count material-icons-chat_bubble_outline">
                        <?php echo $post->getApprovedComments()->count(); ?>
                    </span>
                </a>
            </span>
            <?php endif; ?>
            <div class="social-sharing" style="float: left">
                <a href="https://www.facebook.com/sharer/sharer.php?u=<?= $this->getPostRoute() ?>&display=popup&ref=plugin">
                    <img style="width: 40px" alt="Chia sẻ facebook" title="Chia sẻ facebook"
                         src="https://healthviet.com.vn/static/frontend/Healthviet/theme/vi_VN/Healthviet_SocialLogin/images/facebook_share.png"/>
                </a>
                <a href="#">
                    <img style="width: 40px" alt="Chia sẻ Google+" title="Chia sẻ Google+"
                         src="https://healthviet.com.vn/static/frontend/Healthviet/theme/vi_VN/Healthviet_SocialLogin/images/google_share.png"/>
                </a>
                <a href="#">
                    <img style="width: 40px" alt="Chia sẻ Twitter" title="Chia sẻ Twitter"
                         src="https://healthviet.com.vn/static/frontend/Healthviet/theme/vi_VN/Healthviet_SocialLogin/images/twitter_share.png"/>
                </a>
            </div>
        </div>
        <?php echo $this->getChildHtml('comments'); ?>
        <?php echo $this->getChildHtml('products'); ?>
        <?php echo $this->getChildHtml('posts'); ?>
    </div>
</div>
