<?php

namespace Healthviet\Banner\Model\Banner;

use Healthviet\Banner\Model\ResourceModel\Banner\CollectionFactory;
use Healthviet\Common\Helper\Data;
use Magento\Framework\App\Request\DataPersistorInterface;

class DataProvider extends \Magento\Ui\DataProvider\AbstractDataProvider
{
    protected $dataPersistor;

    protected $loadedData;

    protected $collection;

    protected $healthvietConfiguration;

    protected $mediaUrl;

    /**
     * DataProvider constructor.
     * @param string $name
     * @param string $primaryFieldName
     * @param string $requestFieldName
     * @param CollectionFactory $collectionFactory
     * @param DataPersistorInterface $dataPersistor
     * @param Data $healthvietConfiguration
     * @param array $meta
     * @param array $data
     */

    public function __construct(
        $name,
        $primaryFieldName,
        $requestFieldName,
        CollectionFactory $collectionFactory,
        DataPersistorInterface $dataPersistor,
        Data $healthvietConfiguration,
        array $meta = [],
        array $data = []
    ) {
        $this->collection = $collectionFactory->create();
        $this->dataPersistor = $dataPersistor;
        $this->healthvietConfiguration = $healthvietConfiguration;
        $this->mediaUrl = Data::getMediaUrl();
        parent::__construct($name, $primaryFieldName, $requestFieldName, $meta, $data);
    }

    /**
     * Get data
     *
     * @return array
     */
    public function getData()
    {
        if (isset($this->loadedData)) {
            return $this->loadedData;
        }
        $items = $this->collection->getItems();
        foreach ($items as $model) {
            $id = $model->getId();
            $this->loadedData[$id] = $model->getData();
            $image = $model->getImage();
            $mobileImage = $model->getMobileImage();
            if ($image || $mobileImage) {
                if ($image) {
                    $arrImage = explode('/', $image);
                    $m['image'][0] = [
                        'name' => end($arrImage),
                        'url' => $this->mediaUrl . $image
                    ];
                }

                if ($mobileImage) {
                    $arrMobileImage = explode('/', $mobileImage);
                    $m['mobile_image'][0] = [
                        'name' => end($arrMobileImage),
                        'url' => $this->mediaUrl . $mobileImage
                    ];
                }

                $this->loadedData[$id] = array_merge($this->loadedData[$id], $m);
            }
        }
        $data = $this->dataPersistor->get('healthviet_banner_banner');

        if (!empty($data)) {
            $model = $this->collection->getNewEmptyItem();
            $model->setData($data);
            $this->loadedData[$id] = $model->getData();
            $this->dataPersistor->clear('healthviet_banner_banner');
        }

        return $this->loadedData;
    }

    public function getMeta()
    {
        $noticeIcon = $this->healthvietConfiguration->validateImage(
            Data::IMAGE_BANNER_ICON_MAX_HEIGHT,
            Data::IMAGE_BANNER_ICON_MAX_WIDTH
        );
        $noticeImage = $this->healthvietConfiguration->validateImage(
            Data::IMAGE_BANNER_MAX_HEIGHT,
            Data::IMAGE_BANNER_MAX_WIDTH
        );

        $meta = parent::getMeta(); // TODO: Change the autogenerated stub
        if (isset($noticeIcon)) {
            $meta['general'] = [
                'children' => [
                    'icon' => [
                        'arguments' => [
                            'data' => [
                                'config' => [
                                    'notice' => __($noticeIcon)
                                ]
                            ]
                        ]
                    ],
                ]
            ];
        }

        if (isset($noticeImage)) {
            if (isset($meta['general']["children"])) {
                $meta['general']["children"]["image"] = [
                    'arguments' => [
                        'data' => [
                            'config' => [
                                'notice' => __($noticeImage)
                            ]
                        ]
                    ]
                ];
            } else {
                $meta['general'] = [
                    'children' => [
                        'image' => [
                            'arguments' => [
                                'data' => [
                                    'config' => [
                                        'notice' => __($noticeImage)
                                    ]
                                ]
                            ]
                        ]
                    ]
                ];
            }
        }
        return $meta;
    }
}
