<?php

namespace Healthviet\SocialLogin\Controller\Google;

use Healthviet\SocialLogin\Controller\AbstractConnect;

class Connect extends AbstractConnect
{
    /**
     * @var string
     */
    protected $_exeptionMessage = 'Google login failed.';

    /**
     * @var string
     */
    protected $_type = 'google';

    /**
     * @var string
     */
    protected $_path = '/userinfo';

    /**
     * @var string
     */
    protected $clientModel = '\Healthviet\SocialLogin\Model\Google\Client';

    /**
     * @param $userInfo
     * @return array
     */
    public function getDataNeedSave($userInfo)
    {
        $dataParent = parent::getDataNeedSave($userInfo);

        $data = [
            'email'     => $userInfo['email'],
            'firstname' => $userInfo['given_name'],
            'lastname'  => $userInfo['family_name'],
        ];

        return array_replace_recursive($dataParent, $data);
    }

    /**
     * @param $data
     * @return array
     */
    protected function getProfilePicture($data)
    {
        if (isset($data['picture'])) {
            // reset data for Facebook connection
            $this->_profilePicture['link']      = $data['picture'];
            $pictureExplode                     = explode('.', $this->_profilePicture['link']);
            $this->_profilePicture['extension'] = end($pictureExplode);
            return parent::getProfilePicture($data); // TODO: Change the autogenerated stub
        }
    }
}
