<?php

/**
 * Wrapper for product sections to include title
 *
 * @var Template $block
 * @var Escaper $escaper
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$childHtml = $block->getChildHtml();
$sectionId = $block->getSectionId();
$sectionIdAttribute = $sectionId ? ' id="' . $escaper->escapeHtmlAttr($sectionId) . '"' : '';
?>
<?php if (trim($childHtml) !== "" || $sectionId=="descriptionHeading"): ?>
    <div class="product-full-width-section"<?= /* @noEscape */ $sectionIdAttribute ?>>
        <?php if ($sectionId=="reviews"): ?>
            <div class="product-section-title"><span><?= $escaper->escapeHtml($block->getTitle()); ?></span></div>
        <?php else:?>
            <h2 class="product-section-title"><span><?= $escaper->escapeHtml($block->getTitle()); ?></span></h2>
        <?php endif; ?>

        <?= $block->getChildHtml(); ?>
    </div>
<?php endif; ?>
