<script>
    require(['jquery', 'Magento_Customer/js/customer-data'], function ($, customer) {
        var refreshParent = function () {

            window.opener.location.reload();
            customer.reload();
            window.close();
        };

        <?php $helper = $this->helper('Healthviet\SocialLogin\Helper\SocialLogin'); ?> <?php if($block->isUserLogin()) : ?>
        refreshParent();
        <?php else : ?>
        window.opener.location.href = "<?php echo $block->getSignInUrl(); ?>";
        window.close();
        <?php endif; ?> })</script>