<?php /** * @var $block \Healthviet\SocialLogin\Block\PopupModal\LoginButton */ ?> <script>
    require(['jquery', 'Magento_Ui/js/modal/modal'], function ($, modal) {
        var options = {
            type: 'popup',
            modalClass: 'popup-authentication',
            responsive: true,
            innerScroll: true,
            title: '',
            buttons: []
        };
        modal(options, $('#modal_content'));
        <?php $helper = $this->helper('Healthviet\SocialLogin\Helper\SocialLogin'); ?> var num = <?php echo $block->isUserLogin();?>;
        if (num == 0 && <?= $helper->isButtonEnabledModal() ? 'true':'false'?>) {
            $('.authorization-link a').bind('click', function (e) {
                e.preventDefault();
                $('#modal_content').modal('openModal');
            });
        }
    })</script>