<?php

use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
?>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();
    $showCart = true;
    $description = false;

    ?>
    <div class="block widget block-products-list <?= /* @noEscape */
    $mode ?>">
        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <h2><?= $block->escapeHtml(__($block->getTitle())) ?></h2>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */
            '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */
            $mode ?> <?= /* @noEscape */
            $mode ?>">
                <ol class="product-items <?= /* @noEscape */
                $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $entityId => $_item): ?>
                        <?php
                        $rating = $objectManager->get('Magento\Review\Model\ResourceModel\Review\CollectionFactory');
                        $collection = $rating->create()->addEntityFilter(
                            'product',
                            $_item->getEntityId()
                        );
                        $countVote = $collection->getSize();
                        ?>
                        <?= /* @noEscape */
                        ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                               class="product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <?php if ($discountPercent = $_item->getDiscountPercent()): ?>
                                <div class="discount-label"><?= $discountPercent ?></div>
                            <?php endif; ?>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <h4><?= $block->escapeHtml($_item->getName()) ?></h4>
                                    </a>
                                </strong>

                                <div class="short-name">
                                    <?= $block->escapeHtml($_item->getProductDescName()) ?>
                                </div>

                                <div class="rating-summary">
                                    <div class="rating-result">
                                        <span style="width: 100%;"></span>
                                    </div>
                                    <div class="rating-label rating-number" style="float: right;margin: 0px">
                                        <span><?= $countVote; ?> đánh giá</span>
                                    </div>
                                </div>


                                <div class="product-grid-bottom">
                                    <?= $block->getProductPriceHtml($_item, $type) ?>

                                    <?php if ($showCart): ?>
                                        <div class="product-item-inner">
                                            <div class="product-item-actions">
                                                <?php if ($showCart): ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                            <form <?= $_item->getId() ?>" data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>"  method="post"
                                                            id="product_addtocart_form_<?= /* @noEscape */
                                                            $postParams['data']['product']; ?>">
                                                            <input type="hidden" name="product"
                                                                   value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                            <input type="hidden" name="<?= /* @noEscape */
                                                            Action::PARAM_NAME_URL_ENCODED ?>"
                                                                   value="<?= /* @noEscape */
                                                                   $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                            <?= $block->getBlockHtml('formkey') ?>

                                                            <button type="submit"
                                                                    class="buy-now"
                                                                    data-mage-init='
                                                                                {
                                                                                    "Healthviet_BuyNow/js/buy-now": {
                                                                                        "form": "#product_addtocart_form_<?= /* @noEscape */
                                                                    $postParams['data']['product']; ?>"
                                                                                    }
                                                                                }'
                                                            >
                                                                <span><?= __('Buy Now') ?></span>
                                                            </button>

                                                            <button type="submit"
                                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                    class="action tocart primary">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                            </form>
                                                        <?php else: ?>
                                                            <?php if ($_item->isAvailable()): ?>
                                                                <div class="stock available">
                                                                    <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                                </div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable">
                                                                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                                </div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
    <?php if ($block->getBlockHtml('formkey')): ?>
        <script type="text/x-magento-init">
            {
                ".block.widget [data-role=tocart-form]": {
                    "Magento_Catalog/js/validate-product": {}
                }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>
