<?php
$posts = $this->getPosts();
$dateFormat = $this->getDateFormat();
if($posts->getItems()):
    $titleLength = 50;
?>
<div class="block block-recent-posts">
    <div class="block-title">
        <strong><?php echo __('Recent Posts') ?></strong>
    </div>
    <div class="block-content">
        <ul>
            <?php foreach ($posts as $post):
                $title = $post->getTitle(); ?>
                <li>
                    <div class="">
                        <a href="<?php echo $this->getPostUrl($post); ?>" class="post-image">
                            <img src="<?php echo $post->getImage() ?>" alt="" />
                        </a>
                    </div>
                    <div>
                        <span class="create-date material-icons-access_time">
                            <time><?php echo date($dateFormat, strtotime($post->getCreationTime()));?></time>
                        </span>
                        <h5 class="post-title">
                            <a href="<?php echo $this->getPostUrl($post); ?>">
                                <?php echo mb_substr($post->getTitle(), 0, $titleLength); ?>
                                <?php echo (mb_strlen($post->getTitle()) > $titleLength) ? '...' : '' ?>
                            </a>
                        </h5>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>