<?php
$postCollection = $block->getCollection();
$dateFormat = $this->getDateFormat();

if(!$postCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */ echo __('There are no posts matching the selection.') ?></div>
    </div>
<?php else: ?>
<div class="posts-list-wrapper">
    <!--<div class="toolbar-top">
        <?php /*echo $block->getChildHtml('blog_toolbar'); */?>
    </div>-->
    <!--get first item-->
    <?php $currentPage = $this->getRequest()->getParam('p', 1); ?>
    <?php if($currentPage == 1): ?>
        <?php $i = 0; foreach($postCollection as $post): ?>
            <?php $i++; ?>
            <?php if ($i == 1): ?>
                <div class="block-posts-list block-posts-top" data-post-id="<?php echo $post->getPostId(); ?>">
                    <div class="post-items">
                        <div class="post-item">
                            <div class="item-wrapper">
                                <div class="post-image">
                                    <a href="<?php echo $this->getPostUrl($post); ?>"><img src="<?php echo $post->getImage() ?>" /></a>
                                </div>
                                <div class="post-content">
                                    <span class="post-date"><?php echo date($dateFormat, strtotime($post->getCreationTime()));?></span>
                                    <h3 class="post-title">
                                        <a href="<?php echo $this->getPostUrl($post); ?>"><?php echo $post->getTitle(); ?></a>
                                    </h3>
                                    <p class="post-short-content"><?php echo $block->filterContent($post->getShortContent()); ?></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif;?>
        <?php endforeach;?>
    <?php endif; ?>
    <div class="block-posts-list">
        <ol class="post-items">
            <?php $j = 0; foreach($postCollection as $post): ?>
                <?php
                $j++;
                if ($j == 1 && $currentPage == 1) {
                    continue;
                }
                ?>

                <li class="post-item" data-post-id="<?php echo $post->getPostId(); ?>">
                    <div class="item-wrapper">
                        <!-- Image -->
                        <div class="post-image">
                            <a href="<?php echo $this->getPostUrl($post); ?>"><img src="<?php echo $post->getImage() ?>" /></a>
                        </div>

                        <div class="">
                            <!-- Metadata -->
                            <div class="post-data">
                                <span class="create-date material-icons-access_time">
                                    <time><?php echo date($dateFormat, strtotime($post->getCreationTime()));?></time>
                                </span>
                            </div>

                            <!-- Title -->
                            <div class="post-title">
                                <h3>
                                    <a href="<?php echo $this->getPostUrl($post); ?>"><?php echo $post->getTitle(); ?></a>
                                </h3>
                            </div>

                            <!-- Short Description -->
                            <div class="post-short-content">
                                <?php echo $block->filterContent($post->getShortContent()); ?>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="toolbar-bottom">
        <?php echo $block->getChildHtml('blog_toolbar'); ?>
    </div>
</div>
<?php endif; ?>