<?php
$postCollection = $block->getCollection();
$dateFormat = $this->getDateFormat();

if(!$postCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */ echo __('There are no posts matching the selection.') ?></div>
    </div>
<?php else: ?>
<div class="posts-list-wrapper">
    <!--<div class="toolbar-top">
        <?php /*echo $block->getChildHtml('blog_toolbar'); */?>
    </div>-->
    <div class="block-posts-list">
        <ol class="post-items">
            <?php foreach($postCollection as $post): ?>
                <li class="post-item" data-post-id="<?php echo $post->getPostId(); ?>">
                    <div class="item-wrapper">
                        <!-- Image -->
                        <div class="post-image">
                            <a href="<?php echo $this->getPostUrl($post); ?>"><img src="<?php echo $post->getImage() ?>" /></a>
                        </div>

                        <div class="">
                            <!-- Metadata -->
                            <div class="post-data">
                                <span class="create-date material-icons-access_time">
                                    <time><?php echo date($dateFormat, strtotime($post->getCreationTime()));?></time>
                                </span>
                            </div>

                            <!-- Title -->
                            <div class="post-title">
                                <h3>
                                    <a href="<?php echo $this->getPostUrl($post); ?>"><?php echo $post->getTitle(); ?></a>
                                </h3>
                            </div>

                            <!-- Short Description -->
                            <div class="post-short-content">
                                <?php echo $block->filterContent($post->getShortContent()); ?>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="toolbar-bottom">
        <?php echo $block->getChildHtml('blog_toolbar'); ?>
    </div>
</div>
<?php endif; ?>
