<?php
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <?php
                $rating = $objectManager->get('Magento\Review\Model\ResourceModel\Review\CollectionFactory');
                $collection = $rating->create()->addEntityFilter(
                    'product',
                    $_product->getEntityId()
                );
                $countVote = $collection->getSize();
                ?>
            <li class="item product product-item">
                <div class="product-item-info"
                     id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                     data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = 'left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;';
                    }
                    ?>
                    <?php // Product Image?>
                    <?php if ($discountPercent = $_product->getDiscountPercent()): ?>
                        <div class="discount-label"><?= $discountPercent ?></div>
                    <?php endif; ?>
                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                <h3><?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?></h3>
                            </a>
                        </strong>

                        <div class="short-name">
                            <?= $escaper->escapeUrl($_product->getProductDescName()) ?>
                        </div>

                        <div class="rating-summary">
                            <div class="rating-result">
                                <span style="width: 100%;"></span>
                            </div>
                            <div class="rating-label rating-number" style="float: right;margin: 0px">
                                <span><?= $countVote; ?> đánh giá</span>
                            </div>
                        </div>

                        <div class="product-grid-bottom">
                            <?= /* @noEscape */ $block->getProductPrice($_product) ?>

                            <div class="product-item-inner">
                                <div class="product actions product-item-actions">
                                    <div class="actions-primary">
                                        <?php if ($_product->isSaleable()):?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form"
                                                  data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                                  action="<?= /* @noEscape */ $this->helper('Magento\Catalog\Helper\Product\Compare')->getAddToCartUrl($_product) ?>"
                                                  id="product_addtocart_form_<?= /* @noEscape */ $postParams['data']['product']; ?>"
                                                  method="post">
                                                <?php $options = $block->getData('viewModel')->getOptionsData($_product); ?>
                                                <?php foreach ($options as $optionItem): ?>
                                                    <input type="hidden"
                                                           name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                                                           value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                                <?php endforeach; ?>
                                                <input type="hidden"
                                                       name="product"
                                                       value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                <input type="hidden"
                                                       name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                       value="<?=
                                                       /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                        ?>">
                                                <?= $block->getBlockHtml('formkey') ?>

                                                <button type="submit" class="buy-now"
                                                        data-mage-init='
                                                        {
                                                            "Healthviet_BuyNow/js/buy-now": {
                                                                "form": "#product_addtocart_form_<?= /* @noEscape */ $postParams['data']['product']; ?>"
                                                            }
                                                        }'
                                                        >
                                                    <span><?= __('Buy Now') ?></span>
                                                </button>

                                                <button type="submit"
                                                        title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                        class="action tocart primary"
                                                        disabled>
                                                    <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            </form>
                                        <?php else:?>
                                            <?php if ($_product->isAvailable()):?>
                                                <div class="stock available">
                                                    <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                            <?php else:?>
                                                <div class="stock unavailable">
                                                    <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <?= ($pos && strpos($pos, $viewMode . '-primary')) ?
                                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                            $position,
                                            'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                        ) : '' ?>
                                    <?= ($pos && strpos($pos, $viewMode . '-secondary')) ?
                                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                            $position,
                                            'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                        ) : '' ?>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <?= ($pos && strpos($pos, $viewMode . '-actions')) ?
                /* @noEscape */ $secureRenderer->renderStyleAsTag(
                    $position,
                    'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                ) : '' ?>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate?>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
                "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
            }
        }
    }
    </script>
<?php endif; ?>
