<?php

namespace Healthviet\SocialLogin\Controller\Facebook;

use Healthviet\SocialLogin\Controller\AbstractConnect;

class Connect extends AbstractConnect
{
    /**
     * @var string
     */
    protected $_exeptionMessage = 'Facebook login failed.';

    /**
     * @var string
     */
    protected $_type = 'facebook';

    /**
     * @var string
     */
    protected $_path = '/me?fields=id,name,first_name,last_name,email,picture.type(large)';

    /**
     * @var string
     */
    protected $clientModel = '\Healthviet\SocialLogin\Model\Facebook\Client';

    /**
     * @param $userInfo
     * @return array
     */
    public function getDataNeedSave($userInfo)
    {
        $dataParent = parent::getDataNeedSave($userInfo);

        $data = [
            'email'     => $userInfo['email'],
            'firstname' => $userInfo['first_name'],
            'lastname'  => $userInfo['last_name'],
        ];

        return array_replace_recursive($dataParent, $data);
    }

    /**
     * @param $data
     * @return array
     */
    protected function getProfilePicture($data)
    {
        if (isset($data['picture']['data']['url'])) {
            // reset data for Facebook connection
            $this->_profilePicture['link']      = $data['picture']['data']['url'];
            $size                               = getimagesize($this->_profilePicture['link']);
            $this->_profilePicture['extension'] = image_type_to_extension($size[2]);

            return parent::getProfilePicture($data); // TODO: Change the autogenerated stub
        }
    }
}
